### ISSUE TITLE
Bug: Scrollbars showing up on both axis, but default scrollbars only on one (desired behavior)

### ISSUE THREAD

**Issue by Sheldonfrith** [adoxography/tailwind-scrollbar#10]
I have a div with classname "overflow-y-hidden" which should only show a horizontal scrollbar. If I remove your scrollbar utilities then the default scrollbar shows up as expected (with no vertical scrollbar). However as soon as I add "scrollbar" or "scrollbar-thin" I get scrollbars on both axis, which is not what I want. I will be trying to figure it out on my own, but if anyone's got any ideas about what might be causing this please let me know.

**Comment by Sheldonfrith** [comment]
It appears the issue is that the tailwind-scrollbar plugin is applying the property "overflow: overlay" to my div, which seems to be overriding my overflow-y-hidden. Still working on a solution. Also the 'rounded' utility as described in the docs/readme is not working for me, I had to add it manually to my css file.

**Comment by Sheldonfrith** [comment]
Well I just commented out line 40 of index.js... `overflow: overlay`. Default behavior is restored now (along with the annoying layout changes, but its better than having a useless vertical scrollbar) with the rest of tailwind-scrollbar still working.

**Comment by adoxography** [comment]
I'm glad you found a workaround, but this should really be fixed on the plugin side. Thanks for reporting!
