### ISSUE TITLE
Rounded Bars raises Error

### ISSUE THREAD

**Issue by John-Kiruba** [adoxography/tailwind-scrollbar#103]
The usage of rounded scrollbars `scrollbar-thumb-rounded-full`  raises the following Build Error

![image](https://github.com/user-attachments/assets/66849b5a-9fb2-4003-8562-0a22d4930b9e)

_Am trying to make the thumb rounded_ 

**tailwind.config.ts:** 

` plugins: [
    // ...
    require("tailwind-scrollbar")({ nocompatible: true })({
      preferredStrategy: "pseudoelements",
    }),
  ],
  variants: {
    scrollbar: ["rounded"],
  },`
  
  **globals.css:**
  
  `@layer utilities {
  .custom-scrollbar {
    @apply scrollbar-track-transparent scrollbar-thin scrollbar-thumb-rounded-full scrollbar-thumb-gray-300  transition-colors duration-150 ease-in;
  }
}
`

**code:** 

`        <div className="bg-white custom-scrollbar h-full max-h-48 overflow-y-auto rounded-[calc(100px/10)] p-2 text-sm font-sans shadow-top">
`

Am i missing something or its an issue ?

**Comment by adoxography** [comment]
You're missing something. :)

Have a look at the actual error you're getting: `TypeError: require(...)(...) is not a function`

This error maps to this call you're making:

```javascript
require("tailwind-scrollbar")({ nocompatible: true })({ preferredStrategy: "pseudoelements", })
```

What the error is telling you is that the result of `require("tailwind-scrollbar")({ nocompatible: true })` is not a function, so you can't subsequently invoke it with `({ preferredStrategy: "pseudoelements", })`.

Instead, merge your configs:

```javascript
require("tailwind-scrollbar")({
    nocompatible: true,
    preferredStrategy: "pseudoelements",
})
```
