### ISSUE TITLE
Trouble with scrollbar for whole page (using dark mode)

### ISSUE THREAD

**Issue by harvanchik** [adoxography/tailwind-scrollbar#14]
I'm trying to create a custom scrollbar for the whole page (so not just a single element like seen in the demos).

What I would expected I had to do was add the classes to my `<body>` element.

```html
<body id="body" class="scrollbar-thumb-gray-400 hover:scrollbar-thumb-gray-500 scrollbar-track-gray-300 dark:scrollbar-thumb-blue-600 dark:scrollbar-track-blue-200 scrollbar-thin">
    ...
</body>
```

The problem is that Tailwind adds the `dark` class to the body element, so the dark variants will not work in the `<body>` element itself, but everything below that.

Please note: I do not want to specify a height, because I'd rather it be responsive to whatever the content height is.

I already tried just adding a `<div>` with the classes and have all of my content inside that, but the browser default scrollbar appeared instead of my custom one.

```html
<body id="body">
    <div class="scrollbar-thumb-gray-400 hover:scrollbar-thumb-gray-500 scrollbar-track-gray-300 dark:scrollbar-thumb-blue-600 dark:scrollbar-track-blue-200 scrollbar-thin">
        ...
    <div>
</body>
```

Any suggestions?  Thanks, much appreciated!

**Comment by harvanchik** [comment]
Figured I can just move the `dark` class to the `<html>` element instead.  That fixes my problem.

**Comment by ume-graham** [comment]
Wow, I was literally in the process of typing that suggestion - [that's how the Tailwind docs demo it](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually). Glad you got it sorted out!

**Comment by harvanchik** [comment]
That's funny.  Thanks anyways!
