### ISSUE TITLE
Custom Colors (using extend) are not recognized

### ISSUE THREAD

**Issue by NKnuelle** [adoxography/tailwind-scrollbar#16]
Hi,

thank you for this nice plugin.

I have a problem using it with custom colors. My custom colors work as expected for texts, backgrounds etc. but they do not seem to be recognized by this plugin. For example:
`<div class="overflow-auto scrollbar scrollbar-thumb-<my-custom-color> scrollbar-track-<my-custom-color> h-64">`

Results in the default scrollbars in Firefox. If I use a built-in color like gray-900 it is working as expected. I don't have problems with custom colors with other tailwind classes like text-color-<my-custom-color>

I use NuxtJS and I added Tailwind and the plugin in the config like this:
```
export default {
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
  ],

  tailwindcss: {
    config: {
      theme: {
        extend: {
          screens: {
            'only-small': {'max': '639px'},
          },
          maxHeight: {
            xs: "20rem",
            sm: "24rem",
          },
          colors: {
            custom: {
              blue: {
                DEFAULT: '#0061A7'
              },
              gray: {
                DEFAULT: '#D9DADA'
              },
              green: {
                DEFAULT: '#00963F'
              },
              red: {
                DEFAULT: '#E3000F'
              },
              yellow: {
                DEFAULT: '#FDC300'
              }
            }
          },
          backgroundImage: theme => ({
            'ds-pattern': "url('~/assets/img/ds-background.jpeg')",
          })
        }
      },
      plugins: [
        require('@tailwindcss/forms'),
        require('tailwind-scrollbar'),
      ],
      variants: {
        // ...
        scrollbar: ['rounded']
    }
    }
  },
}
```

**Comment by adoxography** [comment]
Hey, it looks like you've got an extra `custom` key in your config. Per the docs, [colours should be direct children of the `colors` key](https://tailwindcss.com/docs/customizing-colors#extending-the-defaults). E.g.

```javascript
// ...
theme: {
  extend: {
    colors: {
      blue: {
        DEFAULT: '#0061A7'
      },
      // ...
    }
  }
}
```

The bigger mystery to me is why that's working at all for font colours and suchwhatnot.
