### ISSUE TITLE
Scroll bar apply only for desktop

### ISSUE THREAD

**Issue by lohnsonok** [adoxography/tailwind-scrollbar#17]
How to setup scroll bar to only apply on desktop, and default in mobile and tablet ?

**Comment by adoxography** [comment]
Hm, looks like there's a specificity issue that's preventing this from working. What you _should_ be able to do is slap
```js
variants: {
    scrollbar: ['responsive']
}
```
into your config and then use the `lg:scrollbar` utility. I was planning on throwing up another release this weekend, so I'll include a fix that makes this work in it. Thanks for reporting!

**Comment by adoxography** [comment]
Actually, having looked a little more closely into the issue, this is in alignment with how Tailwind currently does it. You'll end up with same kind of behaviour with the transform system; `lg:transform scale-150` _seems_ like it should work, but the resets in the `lg:transform` utility end up overriding the settings in the `scale-150` utility. One could hypothetically get around the issue by throwing `!important` flags on all the `scale-` utilities (or, in this case, the `scrollbar-thumb-` utilities), but this seems like such an obvious answer that if Adam and the rest of the core maintainers haven't put it in, there are likely dragons hiding there.

You can sidestep the issue by prefixing all of the utilities you're using; for example, `lg:scrollbar lg:scrollbar-thumb-gray-900 lg:scrollbar-track-gray-100`.

**Comment by lohnsonok** [comment]
> Actually, having looked a little more closely into the issue, this is in alignment with how Tailwind currently does it. You'll end up with same kind of behaviour with the transform system; `lg:transform scale-150` _seems_ like it should work, but the resets in the `lg:transform` utility end up overriding the settings in the `scale-150` utility. One could hypothetically get around the issue by throwing `!important` flags on all the `scale-` utilities (or, in this case, the `scrollbar-thumb-` utilities), but this seems like such an obvious answer that if Adam and the rest of the core maintainers haven't put it in, there are likely dragons hiding there.
> 
> You can sidestep the issue by prefixing all of the utilities you're using; for example, `lg:scrollbar lg:scrollbar-thumb-gray-900 lg:scrollbar-track-gray-100`.

It work fine. By prefixing with lg: and responsive variant. Thank a lot

**Comment by lohnsonok** [comment]
So please how to hide on leave div scroll ? And show on enter scrollable content
