### ISSUE TITLE
[Bug] Could not find a declaration file for module 'tailwind-scrollbar'.

### ISSUE THREAD

**Issue by leandroatallah** [adoxography/tailwind-scrollbar#2]
```
Could not find a declaration file for module 'tailwind-scrollbar'.

```

Hi! Can you help me with this error?
I'm using Next.JS with Tailwind CSS.

**Comment by sudo-kuro** [comment]
I have this problem using React.JS and Tailwind v2.01
```
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
TypeError: require(...) is not a function
```
Any suggestion?

**Comment by atlanteavila** [comment]
> I have this problem using React.JS and Tailwind v2.01
> 
> ```
> ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
> TypeError: require(...) is not a function
> ```
> 
> Any suggestion?

Just came here for this same reason. Any ideas, I'm using the latest version of Next.js

**Comment by leandroatallah** [comment]
> > I have this problem using React.JS and Tailwind v2.01
> > ```
> > ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
> > TypeError: require(...) is not a function
> > ```
> > 
> > 
> > Any suggestion?
> 
> Just came here for this same reason. Any ideas, I'm using the latest version of Next.js

For now I'm using a class in the tailwind.css file.

```
.disable-scrollbar {
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none;  /* IE 10+ */
}
.disable-scrollbar::-webkit-scrollbar {
    width: 0px;
    background: transparent; /* Chrome/Safari/Webkit */
}
```

**Comment by adoxography** [comment]
@sudo-kuro @atlanteavila that looks like an unrelated issue: it looks like I added an extra `()` to the README when I shouldn't have. (Where I've used this in my own projects, I haven't included it, so I'm not sure what I was thinking in putting that into the README.) Please see 37919c40f5cae6949bbd1a7a7d08edc7b06778e1 for the correct installation instructions.

Sorry about that!

**Comment by adoxography** [comment]
@leandroatallah This is a TypeScript error. I'm not much of a TS user, and I'm having trouble replicating the issue; if you have an example repo that demonstrates the issue, I'd be willing to take a crack at making the plugin TS compliant, though. In the meantime, Google's suggesting that there are some solutions you can use on your end (e.g. [this](https://medium.com/@pjausovec/how-to-fix-error-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8)).
