### ISSUE TITLE
rounded doesn't work

### ISSUE THREAD

**Issue by niklasgrewe** [adoxography/tailwind-scrollbar#20]
Hi, first thanks for this utility plugin 👍 I use the latest version and i want to make my scrollbar rounded, but the following code doesn't work:

```html
<div className="h-64 overflow-auto scrollbar-thin rounded-md" />
```

```html
<div className="h-64 overflow-auto scrollbar-thin scrollbar-thumb-rounded" />
```
What do i need to change, to get this working?

**Comment by SpaceComet** [comment]
Hi @niklasgrewe ,
Did you add `scrollbar: ['rounded']` into the `variants` of your `tailwind.config.js` file?
It should look something like this:
```
module.exports = {
    plugins: [
        require('tailwind-scrollbar')
    ],
    variants: {
        scrollbar: ['rounded']
    }
};
```

[Here](https://tailwind-scrollbar-example.adoxography.repl.co/) are some examples

**Comment by niklasgrewe** [comment]
Sorry i forgot that, my mistake
thank you, it works now
