### ISSUE TITLE
How to auto hide scroll and show scroll?

### ISSUE THREAD

**Issue by dipalab** [adoxography/tailwind-scrollbar#21]
How to auto hide scroll and show scroll  when user will scroll / hover element?

<img width="572" alt="Screen Shot 2021-06-28 at 12 26 30" src="https://user-images.githubusercontent.com/81816206/123584733-134db900-d80c-11eb-9b99-78a14d5de9a1.png">

currenctly scroll always show. i want to hide and only show scrollbar when user will scroll.

How to do it? 

Thanks

**Comment by RVxLab** [comment]
You could try `overflow-y-hidden hover:overflow-y-auto`.

**Comment by adoxography** [comment]
This is a fairly common question, so I included this in the README a while back:

> NB: This plugin styles scrollbars; it does not force them to appear. Use typical CSS techniques to force content to overflow and trigger a scrollbar.

@RVxLab's solution is what you're looking for. :)

**Comment by rickyzhangca** [comment]
> You could try `overflow-y-hidden hover:overflow-y-auto`.

won't work for touch screen

**Comment by RVxLab** [comment]
Touch screen devices typically don’t have scroll bars. It’s not needed there.
