### ISSUE TITLE
Scrollbar thumb variants

### ISSUE THREAD

**Issue by kotx** [adoxography/tailwind-scrollbar#24]
I can't do something like `scrollbar-thumb-transparent hover:scrollbar-thumb-blue-500`
Probably because there are !importants in the generated css

**Comment by adoxography** [comment]
Hm...that *should* work. I'll look into it.

**Comment by adoxography** [comment]
This'll be working in v2. The way the JIT engine handles variants was causing it to not pick up the scrollbar versions.
