### ISSUE TITLE
Scrollbar in chrome is hide

### ISSUE THREAD

**Issue by Hulxv** [adoxography/tailwind-scrollbar#27]
When i use library classes in chrome it make scrollbar hidden but firefox no have any problems , How can make it unhide in chrome ?

* I just use 'scrollbar-thin' class

**Comment by Hulxv** [comment]
Is there anyone?

**Comment by marzuk-zarir** [comment]
same problem!

**Comment by sactw** [comment]
same!

**Comment by ElaineDelgado** [comment]
Same here.

**Comment by adoxography** [comment]
Anybody want to share some code? :)

**Comment by datvnn** [comment]
It is working on chrome and firefox, here is some code
version: tailwind-scrollbar@2.0.1

file: tailwind.config.js
`plugins: [require('tailwind-scrollbar')({ nocompatible: true })],`

file js
```
<ul
      className={`flex flex-nowrap overflow-x-auto scrollbar-thin scrollbar-thumb-gray-300 scrollbar-thumb-rounded-full dark:scrollbar-thumb-red-100`}
    >
     <li
        className={`py-2 border-b-2 border-transparent hover:border-b-2 hover:border-green-800 hover:text-green-600 mx-3.5 relative`}
      >
      {quicklink}
     </li>
</ul>
```

**Comment by adoxography** [comment]
Thanks for the extra confirmation, @datvnn. I'm gonna close this one for now.

For anyone seeing this kind of issue, the usual culprit (in my experience) is confusion around what the plugin's meant to do: it styles scrollbars; it doesn't have anything to say about when they appear. For that, the `overflow` family of utilities are your friend. No need to reinvent the wheel when they're already hanging around. :)
