### ISSUE TITLE
Variants rounded does not resolve

### ISSUE THREAD

**Issue by awnawnawn** [adoxography/tailwind-scrollbar#34]
tailwind.config.js
```js
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('tailwind-scrollbar')
  ],
  variants: {
    scrollbar: ['rounded']
  }
}
```
![Snipaste_2021-12-16_01-04-31](https://user-images.githubusercontent.com/47672657/146231913-1bda9fc1-109c-4c03-8ae8-bad50f29e76a.png)

I am using the `vite` tool, why doesn’t it take effect?

**Comment by viperxeyes** [comment]
It is broken on tailwind 3 , the work around is to modify the code yourself inside the  node_modules folder like I did , it is not perfect but it is working

**Comment by awnawnawn** [comment]
> It is broken on tailwind 3 , the work around is to modify the code yourself inside the node_modules folder like I did , it is not perfect but it is working

Okay, `scrollbar` seems to be added in `tailwind 3.1`
