### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by saini-facundo** [adoxography/tailwind-scrollbar#37]
Hello, I want to use this library in a project that uses typescript. But it shows me this error. How could I fix it? Thank yo
![scroll](https://user-images.githubusercontent.com/67297450/171729327-17a28049-1b9e-496c-a494-732add5e8363.png)
![sc](https://user-images.githubusercontent.com/67297450/171729425-a5e558e4-fcb0-4474-b70d-260913c6a448.png)
u

**Comment by Anandupr2000** [comment]
create new index.d.ts, utilities.d.ts, variants.d.ts at  node_modules\tailwind-scrollbar\src  with content:

declare function plugin(options?: { strategy?: 'base' | 'class' }): Function
export = plugin

it helped me

**Comment by adoxography** [comment]
This'll be in 1.4!

**Comment by adoxography** [comment]
Turned into v2, but Typescript support is included. :)
