### ISSUE TITLE
Opacity on scrollbar

### ISSUE THREAD

**Issue by dillonstreator** [adoxography/tailwind-scrollbar#39]
How would I make any of the scrollbar elements opaque? For instance I want to make the scrollbar thumb opaque. Additionally, I'd probably like to do a hover state to remove the opacity.

**Comment by adoxography** [comment]
Assuming you mean transparent, you could just define a couple of rgba colours in your theme. I'm not sure if I want to go through the process of supporting (e.g.) `scrollbar-opacity` utilities at this point.

**Comment by adoxography** [comment]
Alternatively, while migrating over to Tailwind 3, I added support for Tailwind's opacity modifiers - so you're free to use something like `scrollbar-thumb-red-500/50` to get 50% opacity. Hope that helps!
