### ISSUE TITLE
Support dark theme for tailwind-scrollbar

### ISSUE THREAD

**Issue by meotimdihia** [adoxography/tailwind-scrollbar#4]
Currently, the plugin doesn't work with the dark variant.

**Comment by adoxography** [comment]
Hey, thanks for bringing this up. I've more generally enabled variants in the plugin in [v1.1.2](https://www.npmjs.com/package/tailwind-scrollbar/v/1.1.2). To add dark mode scrollbars utilities, set `'dark'` as a variant for `scrollbar` in the `variants` object in your tailwind config:

```
variants: {
    // ...
    scrollbar: ['dark']
}
```

Of course, you'll also need to have `darkMode` set to `'media'` or `'class'`, but I assume that if you're here asking about dark mode, you've already got that covered. ;)
