### ISSUE TITLE
Missing support for scrollbar appearance and bg-color

### ISSUE THREAD

**Issue by pbiggar** [adoxography/tailwind-scrollbar#47]
I'm converting some CSS to tailwind, and I was able to use this package to convert some of the `-webkit-scrollbar` styles to tailwind. I was not able to convert these ones however, I'm guessing they're not supported yet.

```
.state::-webkit-scrollbar {
    -webkit-appearance: none;
  }
}
```

```
.state2 {
  &::-webkit-scrollbar-corner {
    background-color: transparent;
  }
}
```

**Comment by pbiggar** [comment]
(I popped into the source and saw how I was supposed to use width and height, so I've updated the issue)

**Comment by adoxography** [comment]
What's the effect of `-webkit-appearance: none`? I haven't needed to use it in my testing, but if you've found an environment where it makes a difference, I'd consider just adding it to the base utilities.

For colouring corners, you're looking for `scrollbar-corner-transparent`. :)

**Comment by pbiggar** [comment]
> What's the effect of `-webkit-appearance: none`? I haven't needed to use it in my testing, but if you've found an environment where it makes a difference, I'd consider just adding it to the base utilities.

I'm not actually sure. I ended up removing this and nothing happened.

> For colouring corners, you're looking for `scrollbar-corner-transparent`. :)

That works thanks! I couldn't find a list of available utilities, did I miss something?

**Comment by adoxography** [comment]
No, but you raised a good point so I [added a list to the README](https://github.com/adoxography/tailwind-scrollbar/blob/main/README.md#complete-list-of-utilities). :)

**Comment by pbiggar** [comment]
Oh yeah, that's really great, thanks!
