### ISSUE TITLE
DEPRECATION: adding rounded classes via the variants array is deprecated.

### ISSUE THREAD

**Issue by senbonsakura** [adoxography/tailwind-scrollbar#48]
Started to get this message on npm console after updating the plugin.

`DEPRECATION: adding rounded classes via the variants array is deprecated. Use nocompatible mode instead (i.e. when adding the plugin, use `scrollbarPlugin({ nocompatible: true })`)
`

**Comment by adoxography** [comment]
Is there something confusing about what the message is telling you to do? :)

**Comment by senbonsakura** [comment]
No it tells me to replace the plugin with someone else. Because in the future this could bite me in the ass.

**Comment by adoxography** [comment]
It's asking you to update how you're configuring this plugin by giving you an example. You can see another example [in the README](https://github.com/adoxography/tailwind-scrollbar#configuration), and a warning about this [in the release notes](https://github.com/adoxography/tailwind-scrollbar/releases/tag/v2.0.1).

**Comment by adoxography** [comment]
Closing as this is an issue on the user side, not the plugin side.
