### ISSUE TITLE
Please add custom Arbitrary for  scrollbar width

### ISSUE THREAD

**Issue by nanghadiios** [adoxography/tailwind-scrollbar#49]
It should be allow to custom arbitrary values for scrollbar width like below:
`scrollbar-w-[3px]`

**Comment by nanghadiios** [comment]
i will donate you 100$ for this feature update

**Comment by adoxography** [comment]
`2.1.0-preview.0` is out with this feature.

**Comment by foodornt** [comment]
did he pay you 100$?

**Comment by adoxography** [comment]
He did not! lol
