### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by stoplion** [adoxography/tailwind-scrollbar#5]
`npm install --save-dev tailwind-scrollbar`

```
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      borderWidth: {
        3: '3px',
      },
      colors: {
        'bright-green': '#36D07D',
        'bright-blue': '#36c2d0',
      },
    },
  },
  variants: {},
  plugins: [require('tailwind-scrollbar')],
};

```

```
<div className="scrollbar scrollbar-thin scrollbar-thumb-red-200 scrollbar-track-gray-500">
HI
</div>
```

Not seeing changes..

**Comment by adoxography** [comment]
This plugin is for _styling_ scrollbars, not creating them. Your example element wouldn't have a scrollbar in the first place, so there would be nothing to style. Try something like this (the `text-5xl h-6` just there to force the browser to scroll):

```jsx
<div className="scrollbar-thin scrollbar-thumb-red-200 scrollbar-track-gray-500 text-5xl h-6">
    HI
</div>
```

The thinking here is that forcing a scrollbar to show up whenever the `scrollbar` or `scrollbar-thin` classes are present would prevent the plugin to be used in cases where you want the normal `auto` scrollbar behaviour. I'll spell this out more clearly in the docs, though.

Anyway, let me know if this works!
