### ISSUE TITLE
Custom extended colors requires opacity modifier to work

### ISSUE THREAD

**Issue by IsakViste** [adoxography/tailwind-scrollbar#52]
Following the ["Using CSS variable" of the Tailwind customizing colors guide](https://tailwindcss.com/docs/customizing-colors#using-custom-colors)
I noticed that using my colors with `scrollbar-track` or `scrollbar-thumb` did not work at first.
At first, I thought it was the plugin not working as I saw the scrollbar in its original state/colors, even when using one of the predetermined colors for the track (or thumb).

After some trial and error, I found out that I needed to add the opacity modifier for it to work, it's a minor inconvenience at best, but probably should be noted somewhere to avoid frustration for others in the same situation.

---

### My setup
**globals.css**
```css
@layer base {
  :root {
    --color-surface: 0deg 0% 20%;
    --color-element: 0deg 100% 75%;
  }
}
```

**tailwind.config.js**
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        surface: 'hsl(var(--color-surface) / <alpha-value>)',
        element: 'hsl(var(--color-element) / <alpha-value>)',
      }
    }
  }
}
```

**index.tsx**
```tsx
export default function Home() {
  return (
    <div>
      // THIS WORKS, as it has the "/100" opacity modifier
      <div className="h-screen scrollbar scrollbar-track-surface/100 scrollbar-thumb-element/100"></div>

      // This does not work, as it does not have the opacity modifier
      <div className="h-screen scrollbar scrollbar-track-surface scrollbar-thumb-element"></div>


      // When one of the elements has a custom color without opacity modifier, the other element won't render as expected
      // This does not work: the track is not yellow (original state gray)
      <div className="h-screen scrollbar scrollbar-track-yellow-500 scrollbar-thumb-element"></div>

      // This does not work: the thumb is not yellow (original state light-gray)
      <div className="h-screen scrollbar scrollbar-track-surface scrollbar-thumb-yellow-500"></div>
    </div>
  }
}
```

I hope this is clear, I'm happy to provide with more files or information if necessary 🙂

**Comment by adoxography** [comment]
Hey, sorry, this issue slipped past my radar; just seeing it now. Thanks for all the detail you've included. Looks like this is a bug in the documentation Tailwind provides for plugin authors. I was able to put in a fix for the plugin, though.

**Comment by jameslounds** [comment]
Can we get a release on npm for this patch please
