### ISSUE TITLE
Firefox styling is different in OSX Firefox

### ISSUE THREAD

**Issue by dostongulmatov** [adoxography/tailwind-scrollbar#53]

**Comment by adoxography** [comment]
Hiya! I'm going to need more information than that. In particular:

- What OS are you using?
- What version of Firefox are you using?
- What does the code that you're using the plugin with look like?
- Can you confirm that that code is working in Chrome?

**Comment by dostongulmatov** [comment]
sure
 - Using Mac OS version 12.6 
 - Firefox version 107.0
 - I am using React so 
    in tailwind.config.js
```
     plugins: [
    require('tailwind-scrollbar')({ nocompatible: true }),
    require('autoprefixer')
  ],
```
and scrollbar.tsx component

```
interface Props {
  children: ReactNode;
  className?: string;
}
export default function Scrollbar({ children, className }: Props) {
  return (
    <div
      className={`overflow-y-auto scrollbar-thin scrollbar-thumb-greyWhite scrollbar-thumb-rounded-full ${className}`}
    >
      {children}
    </div>
  );
}
```

- yes in Chrome and Safari it is working perfectly

**Comment by dostongulmatov** [comment]
After adding overflow-y-auto it started working but the styling is different from chrome and safari

**Comment by adoxography** [comment]
Apparently, this is a known [issue/feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1513602) with Firefox on OSX. Nothing that can be done about it. I can look into adding it to the docs, though.
