### ISSUE TITLE
Cannot adjust thumb and track size independently

### ISSUE THREAD

**Issue by VladLshnk0** [adoxography/tailwind-scrollbar#68]
For example it's impossible to made a thumb wider then track

**Comment by adoxography** [comment]
Correct, that is a browser limitation. Firefox exposes a single `scrollbar-width` property, and the others respect `width` on the `::-webkit-scrollbar` pseudoelement but not on `::-webkit-scrollbar-track` or `::-webkit-scrollbar-thumb`. If you want anything more than what the browsers natively offer, you'll need to look into fully custom scrollbar elements.
