### ISSUE TITLE
Add display: block to ::-webkit-scrollbar

### ISSUE THREAD

**Issue by silveltman** [adoxography/tailwind-scrollbar#70]
This would allow us to enable scrollbar with this plugin, when it is set on display: none.

For example, DaisyUI's carousel hides the scrollbar. I would like to have it shown automatically when using this plugin.

DaisyUI carousel: https://daisyui.com/components/carousel/#slide2

temporary solution: 
```
<style lang="postcss">
	:global(.carousel::-webkit-scrollbar) {
		display: block !important;
	}
</style>
```

**Comment by adoxography** [comment]
Added in `3.0.1` 👍
