### ISSUE TITLE
"scrollbar-none" invalid on chromium when switch from 2.1.0 to 3.0.0.

### ISSUE THREAD

**Issue by buddhiko1** [adoxography/tailwind-scrollbar#73]
tailwindcss
```
  .g-scrollbar {
    @apply scrollbar-thin scrollbar-w-1.5 scrollbar-thumb-border scrollbar-track-background;
  }

  .g-scrollbar-dark {
    @apply scrollbar-thin scrollbar-w-1.5 scrollbar-thumb-border-dark scrollbar-track-background-dark;
  }

  .g-scrollbar-hide {
    @apply scrollbar-none;
  }
```
code:
```
    document.documentElement.classList.remove('g-scrollbar');
    document.documentElement.classList.remove('g-scrollbar-dark');
    document.documentElement.classList.add('g-scrollbar-hide');
```

when switching back to 2.1.0, it can work properly.

What are the benefits for me to upgrade?

**Comment by adoxography** [comment]
I need more to go on than this. What are you seeing that is making you think that it's invalid? In general, when filing a bug report anywhere, try to include all of the following:

1. What you did
2. What you expected to happen
3. What actually happened

**Comment by buddhiko1** [comment]
Sorry, my English is very poor.
I want to hide the scrollbar with "scrollbar-none".

![last](https://github.com/adoxography/tailwind-scrollbar/assets/8435488/2a0bb986-bfb4-401c-a17b-82d4ebd19325)


 It can work properly at version 2.1.0.
But, when I upgrade to version 3.0.0, it can't hide the scrollbar.

Thanks for your project.

**Comment by adoxography** [comment]
I understand that you're trying to use the `scrollbar-none` utility. I need to know how you're using it to be of any help. Do you have a small code snippet that you're using to run this test between versions?

**Comment by buddhiko1** [comment]
My code
```
  .g-scrollbar-hide {
    @apply scrollbar-none;
  }

document.documentElement.classList.add('g-scrollbar-hide');
```

**Comment by adoxography** [comment]
I'm getting the feeling that you're trying to use `scrollbar-none` to toggle off an existing scrollbar setting. That won't work (and has never worked) - see the screenshot you posted:

> Because of browser quirks, this cannot be used to hide an existing styled scrollbar

When used on its own simply to hide a normal (i.e. unstyled) scrollbar, it's working as expected for me, and I have tests to verify that the CSS that's generated for `scrollbar-none` has not changed between 2.1.0 and 3.0.0.

**Comment by buddhiko1** [comment]
Ok, thanks for your replay~
