### ISSUE TITLE
Plugin breaks TailwindPlay

### ISSUE THREAD

**Issue by silveltman** [adoxography/tailwind-scrollbar#75]
I wanted to submit another issue, but ran into a problem creating a TailwindPlay example.

Error: 
`h.default is not a function`

Link: 
https://play.tailwindcss.com/51IAN2oNqp?file=config

![CleanShot 2023-05-14 at 10 13 31](https://github.com/adoxography/tailwind-scrollbar/assets/52583398/3ac8808c-5c1c-4ac3-a8a4-d1026304835e)

**Comment by adoxography** [comment]
Got it sorted out. Your link's working now. :)
