### ISSUE TITLE
Tailwind Scrollbar not showing

### ISSUE THREAD

**Issue by chromaticmoe** [adoxography/tailwind-scrollbar#81]
Tailwind Scrollbar being crossed out in its CSS Rules. I don't know if this is what's causing my scrollbar to not appear.

![image](https://github.com/adoxography/tailwind-scrollbar/assets/122515859/6348ddca-3ee0-4378-bf27-ec87ee7d8630)

Below is my code and where am I using it.

```
'use client';

import Header from "@/app/components/header/header";
import About from "@/app/components/about/about";
import ParticlesBackground from "@/app/components/particles-js/particlesbackground";
import Work from "@/app/components/work/work";

export default function Home() {
  return (
    <div className="relative overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-color-bg-variant/20  scrollbar-thumb-color-primary/80">
      <ParticlesBackground />
      <Header />
      <About />
      <Work />
    </div>
    
  )
}

```

**Comment by adoxography** [comment]
Rules being crossed out is expected. Chrome (et al.) and Firefox use two wildly different methods for styling scrollbars, so the techniques for one browser will be detected as invalid by the other.

The first thing I'd check here is that the scrollbar you're seeing actually belongs to the element you're styling. That one looks to me like it could be owned by the `body` or `html` elements. If you take out your `overflow-y-scroll` and still see a scrollbar, that would confirm it.

**Comment by chromaticmoe** [comment]
> Rules being crossed out is expected. Chrome (et al.) and Firefox use two wildly different methods for styling scrollbars, so the techniques for one browser will be detected as invalid by the other.
> 
> The first thing I'd check here is that the scrollbar you're seeing actually belongs to the element you're styling. That one looks to me like it could be owned by the `body` or `html` elements. If you take out your `overflow-y-scroll` and still see a scrollbar, that would confirm it.

Thank you so much!! That solves my problem.
