### ISSUE TITLE
Live demo is not working

### ISSUE THREAD

**Issue by adam-binks** [adoxography/tailwind-scrollbar#85]
I'm getting an SSL error: https://tailwind-scrollbar-example.adoxography.repl.co/

If I change it to http://, I get this:
<img width="631" alt="image" src="https://github.com/adoxography/tailwind-scrollbar/assets/13518594/dd03e63c-02f9-4f7a-aa1c-1fb5dbb3fc03">

**Comment by leeyucha** [comment]
me too.
in my case 
![image](https://github.com/adoxography/tailwind-scrollbar/assets/107383057/9d5125ea-30cd-468e-a832-e4321dac8806)

**Comment by adoxography** [comment]
I've been putting off creating a proper documentation site. It's up [here](https://adoxography.github.io/tailwind-scrollbar/examples), and it should supercede the old demo site.
