### ISSUE TITLE
scrollbar-thumb-rounded-full doesn't work with custom tailwind borderRadius?

### ISSUE THREAD

**Issue by arkmech** [adoxography/tailwind-scrollbar#89]
I have replaced the existing `borderRadius` with my own `borderRadius` in my `tailwind.config.js`. 

```
    borderRadius: {
      DEFAULT: '0.5rem',
      none: '0rem',
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.625rem',
      full: '9999px',
    },
```
When I do this, it seems borderRadius doesn't work? `scrollbar-thumb-rounded-full`

On Chrome

**Comment by arkmech** [comment]
My element does contain `scrollbar-thumb-rounded-full` class, but the style does not show on styles like how the docs have it:

```
.scrollbar-thumb-rounded-full {
    --scrollbar-thumb-radius: 9999px;
}
```

**Comment by adoxography** [comment]
I'm having trouble reproducing this. For reference, I'm using this `tailwind.config.js`:

```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [...],
  theme: {
    borderRadius: {
      DEFAULT: '0.5rem',
      none: '0rem',
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.625rem',
      full: '9999px'
    }
  },
  plugins: [
    require('tailwind-scrollbar')({
      nocompatible: true
    })
  ]
};
```

Applying `scrollbar-thumb-rounded-full` to an element adds the `--scrollbar-thumb-radius: 9999px` as expected.

The two things I can think of that could be different for you would be (a) you're not using [nocompatible mode](https://adoxography.github.io/tailwind-scrollbar/getting-started#configuration) or (b) your overrides are in the wrong place in your configuration.

**Comment by arkmech** [comment]
> I'm having trouble reproducing this. For reference, I'm using this `tailwind.config.js`:
> 
> ```js
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   content: [...],
>   theme: {
>     borderRadius: {
>       DEFAULT: '0.5rem',
>       none: '0rem',
>       sm: '0.375rem',
>       md: '0.5rem',
>       lg: '0.625rem',
>       full: '9999px'
>     }
>   },
>   plugins: [
>     require('tailwind-scrollbar')({
>       nocompatible: true
>     })
>   ]
> };
> ```
> 
> Applying `scrollbar-thumb-rounded-full` to an element adds the `--scrollbar-thumb-radius: 9999px` as expected.
> 
> The two things I can think of that could be different for you would be (a) you're not using [nocompatible mode](https://adoxography.github.io/tailwind-scrollbar/getting-started#configuration) or (b) your overrides are in the wrong place in your configuration.

Fixed: I was not using nocompatible mode. Thank you
