### ISSUE TITLE
scrollbar-h does not work as expected

### ISSUE THREAD

**Issue by JamshedK** [adoxography/tailwind-scrollbar#95]
I have the `nocompatible` mode setup, however the scrollbar-h does not seem to be working as expected. 

Here is the div where I'm using the scrollbar

```        
<div
    className="bg-[#142838] max-h-screen overflow-y-auto scrollbar 
          scrollbar-thumb-[#ffffff] scrollbar-thumb-rounded-full text-[14px] 
          pb-10 pt-6 sticky top-0 scrollbar-w-2 scrollbar-h-4"
  >
    {topologyJSON.map((item, index) => (
      <IntentionBox
        selectedItem={selectedItem}
        key={index}
        title={item.intention_type}
        intentionList={item.intention_list}
        onSelectItem={handleSelectItem}
        ratings={ratings}
      />
    ))}
  </div>
 ```
        
However, `scrollbar-w` does work as expected as you can see on this screenshot. 
        
<img width="330" alt="image" src="https://github.com/adoxography/tailwind-scrollbar/assets/47409663/ce1bbc82-96d7-4d94-8bc8-7fb650f2e3d7">

I'm using both Microsoft Edge and Chrome. As you can see, the scrollbar height is still pretty big. Any ideas on why that could be the case? 

P.S: This is the first time I'm raising an issue on GitHub since I'm a student, so please do let me know if I needed to include something.

**Comment by adoxography** [comment]
Hey there, for a vertical scrollbar, you'll want to use the `scrollbar-w` utility. (Vertical scrollbars implicitly have a height of 100%; the only thing that would be reasonable to change about them is their width.) `scrollbar-h` is really only meaningful when you have a horizontal scrollbar.

**Comment by JamshedK** [comment]
Oh that makes sense. Is that a browser default that the height of a vertical scrollbar is always 100%? I have seen vertical scrollbars that are very short so was wondering how that is done.

**Comment by adoxography** [comment]
Just so we're on the same page here - there's two components you could be talking about: the scrollbar itself and the scrollbar thumb (the thing you click and drag). Vertical scrollbars always take up the full height of their container, which is a pretty universal design pattern - and yes, it is enforced by the browser. The height of the thumb is dictated by the ratio of the height of the visible content to the total scroll area. Its size lets you know how much content is hidden in relation to what you're seeing.

**Comment by JamshedK** [comment]
Oh thank you so much. That makes a lot more sense.
